apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: default
spec:
  clusterIP: None
  ports:
    - name: kafka
      port: 9092
      protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: kafka
  namespace: default
subsets:
  - addresses:
      - ip: 10.0.0.177 #mac local host ip address
    ports:
      - port: 9092
        name: kafka
        protocol: TCP
